package com.xinda.counterfeit.pojo;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_da_area.areaid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_da_area.codeid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    private Integer codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_da_area.parentid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_da_area.cityName
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_da_area.areaid
     *
     * @return the value of tb_da_area.areaid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_da_area.areaid
     *
     * @param areaid the value for tb_da_area.areaid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_da_area.codeid
     *
     * @return the value of tb_da_area.codeid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_da_area.codeid
     *
     * @param codeid the value for tb_da_area.codeid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_da_area.parentid
     *
     * @return the value of tb_da_area.parentid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_da_area.parentid
     *
     * @param parentid the value for tb_da_area.parentid
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_da_area.cityName
     *
     * @return the value of tb_da_area.cityName
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_da_area.cityName
     *
     * @param cityName the value for tb_da_area.cityName
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }
}