package com.xinda.counterfeit.mapper;

import java.util.List;
import java.util.Map;

import com.xinda.counterfeit.pojo.Area;


public interface AreaMapper {
    //获得地区
    List<Map<String, Object>> selectByParam(Map<String, Object> param);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_da_area
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    int deleteByPrimaryKey(Integer areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_da_area
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_da_area
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_da_area
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    Area selectByPrimaryKey(Integer areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_da_area
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_da_area
     *
     * @mbggenerated Mon Apr 17 11:03:19 CST 2017
     */
    int updateByPrimaryKey(Area record);
    Area selectName(Map<String, Object> map);
}